require("core.plugin_config.gruvbox")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.lsp")
require("core.plugin_config.null-ls")
require("core.plugin_config.prettier")
require("core.plugin_config.fugitive")
require("core.plugin_config.comment")
require("core.plugin_config.nvim-surround")

